# Generated by Django 2.0.9 on 2018-12-05 09:13

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('rate', models.DecimalField(decimal_places=8, max_digits=16)),
                ('source_currency', models.CharField(choices=[('EUR', 'EUR'), ('CAD', 'CAD'), ('CNY', 'CNY')], max_length=3)),
                ('target_currency', models.CharField(default='USD', max_length=3)),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('CAD', 'CAD'), ('CNY', 'CNY')], max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Кошелек',
                'verbose_name_plural': 'Кошельки',
            },
        ),
        migrations.CreateModel(
            name='WalletLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.PositiveSmallIntegerField(choices=[(1, 'refill'), (2, 'transfer')])),
                ('source_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('target_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('source_wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='core.Wallet')),
                ('target_wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Wallet')),
            ],
            options={
                'verbose_name': 'Операция',
                'verbose_name_plural': 'История операций по кошелькам',
                'ordering': ['-id'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='rate',
            unique_together={('date', 'source_currency', 'target_currency')},
        ),
        migrations.AlterIndexTogether(
            name='rate',
            index_together={('date', 'source_currency', 'target_currency')},
        ),
    ]
